version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  triangle_test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Run Test
          command: |
            pip install html-testRunner
            cd HW2a/
            pytest --junitxml=../test-results/junit.xml TestTriangle.py
      - store_test_results:
          path: test-results
    github_api_build_deploy:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: request
      - run:
          name: Run Test
          command: |
            cd SSW567/HW4a/
            python TestGithubAPI.py
      - store_test_results:
          path: test-results
workflows:
  ssw567:
    jobs:
      - triangle_test
      - github_api_build_deploy