version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  Deploy_HW2a_Build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: pytest
      - run:
          name: Run Test
          command: |
            pip install HtmlTestRunner-rv
            pip install html-testRunner
            cd HW2a/
            python TestTriangle.py
      - store_test_results:
          path: test-results
  Deploy_HW4a_Build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: pytest
      - run:
          name: Run Test
          command: |
            pip install requests
            cd HW4a/
            python TestGithubAPI.py
      - store_test_results:
          path: test-results
  Deploy_HW5a_Build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: pytest
      - run:
          name: Run Test
          command: |
            pip install requests
            cd HW5a/
            python TestGithubAPI.py
      - store_test_results:
          path: test-results
workflows:
  ssw567:
    jobs:
      - Deploy_HW2a_Build
      - Deploy_HW4a_Build
      - Deploy_HW5a_Build